### ISSUE TITLE
Error message unsandboxing error

### ISSUE THREAD

**Issue by bewl87** [opa334/libSandy#1]
![image](https://user-images.githubusercontent.com/49694850/184324352-c0f4b35a-5264-4a5f-9868-f1f84d95a931.png)![image](https://user-images.githubusercontent.com/49694850/184324381-25b4cb53-b476-49dc-9158-ebefe55ea4ac.png)![image](https://user-images.githubusercontent.com/49694850/184324412-bbee7b0b-6cd1-4106-9717-3b27fd859b55.png)

appears to not be working on my iphone x ios 13.3 unless i'm not using it correctly.

**Comment by opa334** [comment]
works fine for me on iPhone X 13.7.

What jailbreak?

Also before you do anything, install CocoaTop64 from BigBoss, open the CocoaTop app, find "MobileGestaltHelper" in the process list, tap it, press the 3 lines at the top right, select "Modules" and check whether libSandySupport.dylib is in that list (sort by size, only third party libraries have a size in that table). Please also send a screenshot of the top of that modules list when sorted by size.

Afterwards please try restarting the MobileGestaltHelper process via CocoaTop and try again.

**Comment by opa334** [comment]
nevermind, I know the issue, uninstall the tweak "StopCrashingPls", then libSandy will start working

**Comment by bewl87** [comment]
can confirm this solved the issue i was having
