### ISSUE TITLE
libSandy.m:3:9: fatal error: 'xpc/xpc.h' file not found

### ISSUE THREAD

**Issue by Shapa7276** [opa334/libSandy#4]
Getting below error where can I find  headers files 

==> Compiling libSandy.m (armv7)…
libSandy.m:3:9: fatal error: 'xpc/xpc.h' file not found
#import <xpc/xpc.h>
        ^~~~~~~~~~~
1 error generated.

I tried few from  https://opensource.apple.com/source/X11server/X11server-106.3/kdrive/xorg-server-1.6.5-apple3

seems to be not working

**Comment by opa334** [comment]
You need to copy the header from the `iphone/xpc_service` theos template.
